services:
  
  strapi-db:
    image: beercan1989/arm-mysql:latest
    profiles: ["mysql"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: upassword
      MYSQL_DATABASE: strapi_db
      MYSQL_ROOT_PASSWORD: rpassword
    volumes: # Optional, same as -v in docker run
      -  mysql-data:/VAR/LIB/MYSQL
    networks:
      - strapi-network

  strapi-mysql:
    build: 
      context: .
      dockerfile: mysql.dockerfile
      args:
        - PORTS=1337
        - NAME=mysql-project
        - DBCLIENT=mysql
        - DBHOST=strapi-db
        - DBPORT=3306
        - DBNAME=strapi_db
        - DBUSER=user
        - DBPASS=upassword
    profiles: ["mysql"]
    depends_on:
      - strapi-db
    env_file:
      - ./mysql/.env
    ports:
      # - "80" # user this for production - port 80 ${PORT}
      - 1337:1337 # gets port number from .env file, so if you change it there it updates it here
    volumes: # Optional, same as -v in docker run
      -  ./mysql/config/server.js:/app/$NAME/config/server.js
      -  ./mysql/config/public:/app/$NAME/public
    networks:
      - strapi-network

  strapi-plugins:
    build: 
      context: .
      dockerfile: plugins.dockerfile
      args:
        - NAME=test-project
    profiles: ["plugins"]
    env_file:
      - plugins/.env
    ports:
      # - "80" # user this for production - port 80 ${PORT}
      - ${PORT}:${PORT} # gets port number from .env file, so if you change it there it updates it here
    volumes: # Optional, same as -v in docker run
      -  ${PWD}/plugins-config/server.js:/app/$NAME/config/server.js
      -  ${PWD}/plugins-db:/app/$NAME/.tmp
      -  ${PWD}/plugins-public:/app/$NAME/public
    networks:
      - strapi-network

  strapi-plain:
    build: 
      context: .
      dockerfile: plain.dockerfile
      args:
        - NAME=plain-project
    profiles: ["plain"]
    env_file:
      - plain/.env
    ports:
      # - "80" # user this for production - port 80 ${PORT}
      - ${PORT}:${PORT} # gets port number from .env file, so if you change it there it updates it here
    volumes: # Optional, same as -v in docker run
      -  ${PWD}/plain-config/server.js:/app/$NAME/config/server.js
      -  ${PWD}/plain-db:/app/$NAME/.tmp
      -  ${PWD}/plain-public:/app/$NAME/public
    networks:
      - strapi-network

networks: # Optional, same as docker network create
  strapi-network:

volumes:
  mysql-data: